<?php if ($this->isTagalysEnabled()): ?>
    <?php
        $eventDetails = false;
        try {
            $thisProduct = $this->getMainProduct();
            if ($thisProduct != false) {
                $eventDetails = array(
                    'action' => 'view',
                    'sku' => $thisProduct->getSku()
                );
            }
        } catch (Exception $e) {
            // don't log this as it might happen too often
        }
    ?>
    <?php if ($eventDetails != false): ?>
        <script>
            require(['jquery', 'jquery/ui'], function($){ 
                try {
                    $(document).on('tagalys:ready', function() {
                        try {
                            $.fn.tagalys_analytics.track_event('product_action', <?php echo json_encode($eventDetails) ?>);
                        }
                        catch(err) {
                            
                        }
                    });
                }
                catch(err) {
                    
                }
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
